### ISSUE TITLE
Questions for clarification

### ISSUE THREAD

**Issue by saile3** [xpes/webapp23-FitflexStudio#1]
1: Do The member ID and Trainers ID the same? Can a Trainer be a member?
2: Do we have address for the members. if yes, can a member have multiple address?
3: What are the different duration options for the membership?
4: Can we change the name of the classes to fitnessClass

**Comment by huda46** [comment]
Hello, I would like to also clarify these details:

1: Regarding the class member, we added a constraint that says that a trainer or member must be at least 16 years old, do you agree on that?
2: Also for the payment details, we represented it with IBAN, this means that a member/trainer should give only his IBAN to pay/be paid, do you agree on that of you want to add other payment details?
3: regarding the fitnessClass class, we defined the capacity of each class to 20, do you agree on that?

thank you

**Comment by huda46** [comment]
We posted the domain model example, could you please take a look at it and give us your feedback?

**Comment by sahajmajavdia** [comment]
Member ID and Trainer ID are different; a trainer can't be a member. Members can have only a single address. Membership can be for 3,6,12 months. Class name is fine

**Comment by sahajmajavdia** [comment]
Age constraint is acceptable to work with 16 years. For payment, IBAN and offline payment should be good. If you can add an option to pay offline in cash. 20 class numbers are agreed upon.

**Comment by saile3** [comment]
closing this issue any unanswered question can be raised as a new question
