### ISSUE TITLE
How are the different membership classified 

### ISSUE THREAD

**Issue by saile3** [xpes/webapp23-FitflexStudio#3]
we would like to understand how are the different memberships classified. i.e. how is each membership plan different from the others? is it only the duration?

**Comment by sahajmajavdia** [comment]
Duration and price.

**Comment by saile3** [comment]
Thanks, we had added some extra parameters called services that we thought would differentiate the membership plan.  So every membership offers training.  If a member gets a membership is it mandatory for him to take a class?

**Comment by xpes** [comment]
No ,classes are not mandatory, basic membership should allocate people to classes while premium members should have an option to choose their own classes and/or a personal trainer

**Comment by saile3** [comment]
ok, will add a property called services that can also distinguish between different membership
